modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="sswplus"
version="${file.jarVersion}"
displayName="Slabs Stairs Walls +"
authors="gayannabeth"
description='''
Adds a ton of extra slabs stairs and walls based on vanilla blocks
'''
[[dependencies.sswplus]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sswplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sswplus]]
	modId="annabethscore"
	mandatory=true
	versionRange="[1.0,)"
	ordering="AFTER"
	side="BOTH"
