package annabeth.sswplus.tags;

import annabeth.sswplus.SSWPlusMain;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.tags.BlockTags;
import net.minecraft.tags.ItemTags;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.common.Tags.IOptionalNamedTag;

public class SSWPTags {
	public static class BlockTagList {
		public static final IOptionalNamedTag<Block> WOODEN_WALLS = create("wooden_walls");
		public static final IOptionalNamedTag<Block> GLASS_SLABS = create("glass_slabs");
		public static final IOptionalNamedTag<Block> GLASS_STAIRS = create("glass_stairs");
		public static final IOptionalNamedTag<Block> GLASS_WALLS = create("glass_walls");
		public static final IOptionalNamedTag<Block> COLORED_GLASS_SLABS = create("colored_glass_slabs");
		public static final IOptionalNamedTag<Block> COLORED_GLASS_STAIRS = create("colored_glass_stairs");
		public static final IOptionalNamedTag<Block> COLORED_GLASS_WALLS = create("colored_glass_walls");
		public static final IOptionalNamedTag<Block> TERRACOTTA_SLABS = create("terracotta_slabs");
		public static final IOptionalNamedTag<Block> TERRACOTTA_STAIRS = create("terracotta_stairs");
		public static final IOptionalNamedTag<Block> TERRACOTTA_WALLS = create("terracotta_walls");
		public static final IOptionalNamedTag<Block> COLORED_TERRACOTTA_SLABS = create("colored_terracotta_slabs");
		public static final IOptionalNamedTag<Block> COLORED_TERRACOTTA_STAIRS = create("colored_terracotta_stairs");
		public static final IOptionalNamedTag<Block> COLORED_TERRACOTTA_WALLS = create("colored_terracotta_walls");
		public static final IOptionalNamedTag<Block> CONCRETE_SLABS = create("concrete_slabs");
		public static final IOptionalNamedTag<Block> CONCRETE_STAIRS = create("concrete_stairs");
		public static final IOptionalNamedTag<Block> CONCRETE_WALLS = create("concrete_walls");
		public static final IOptionalNamedTag<Block> ANDESITE = create("andesite");
		public static final IOptionalNamedTag<Block> ANDESITE_SLABS = create("andesite_slabs");
		public static final IOptionalNamedTag<Block> ANDESITE_STAIRS = create("andesite_stairs");
		public static final IOptionalNamedTag<Block> ANDESITE_WALLS = create("andesite_walls");
		public static final IOptionalNamedTag<Block> DIORITE = create("diorite");
		public static final IOptionalNamedTag<Block> DIORITE_SLABS = create("diorite_slabs");
		public static final IOptionalNamedTag<Block> DIORITE_STAIRS = create("diorite_stairs");
		public static final IOptionalNamedTag<Block> DIORITE_WALLS = create("diorite_walls");
		public static final IOptionalNamedTag<Block> GRANITE = create("granite");
		public static final IOptionalNamedTag<Block> GRANITE_SLABS = create("granite_slabs");
		public static final IOptionalNamedTag<Block> GRANITE_STAIRS = create("granite_stairs");
		public static final IOptionalNamedTag<Block> GRANITE_WALLS = create("granite_walls");
		public static final IOptionalNamedTag<Block> BASALT = create("basalt");
		public static final IOptionalNamedTag<Block> BASALT_SLABS = create("basalt_slabs");
		public static final IOptionalNamedTag<Block> BASALT_STAIRS = create("basalt_stairs");
		public static final IOptionalNamedTag<Block> BASALT_WALLS = create("basalt_walls");
		public static final IOptionalNamedTag<Block> BLACKSTONE = create("blackstone");
		public static final IOptionalNamedTag<Block> BLACKSTONE_SLABS = create("blackstone_slabs");
		public static final IOptionalNamedTag<Block> BLACKSTONE_STAIRS = create("blackstone_stairs");
		public static final IOptionalNamedTag<Block> BLACKSTONE_WALLS = create("blackstone_walls");
		public static final IOptionalNamedTag<Block> NETHER_BRICKS = create("nether_bricks");
		public static final IOptionalNamedTag<Block> NETHER_BRICK_SLABS = create("nether_brick_slabs");
		public static final IOptionalNamedTag<Block> NETHER_BRICK_STAIRS = create("nether_brick_stairs");
		public static final IOptionalNamedTag<Block> NETHER_BRICK_WALLS = create("nether_brick_walls");
		public static final IOptionalNamedTag<Block> PRISMARINE = create("prismarine");
		public static final IOptionalNamedTag<Block> PRISMARINE_SLABS = create("prismarine_slabs");
		public static final IOptionalNamedTag<Block> PRISMARINE_STAIRS = create("prismarine_stairs");
		public static final IOptionalNamedTag<Block> PRISMARINE_WALLS = create("prismarine_walls");
		public static final IOptionalNamedTag<Block> QUARTZ = create("quartz");
		public static final IOptionalNamedTag<Block> QUARTZ_SLABS = create("quartz_slabs");
		public static final IOptionalNamedTag<Block> QUARTZ_STAIRS = create("quartz_stairs");
		public static final IOptionalNamedTag<Block> QUARTZ_WALLS = create("quartz_walls");
		public static final IOptionalNamedTag<Block> SANDSTONE = create("sandstone");
		public static final IOptionalNamedTag<Block> SANDSTONE_SLABS = create("sandstone_slabs");
		public static final IOptionalNamedTag<Block> SANDSTONE_STAIRS = create("sandstone_stairs");
		public static final IOptionalNamedTag<Block> SANDSTONE_WALLS = create("sandstone_walls");
		public static final IOptionalNamedTag<Block> RED_SANDSTONE = create("red_sandstone");
		public static final IOptionalNamedTag<Block> RED_SANDSTONE_SLABS = create("red_sandstone_slabs");
		public static final IOptionalNamedTag<Block> RED_SANDSTONE_STAIRS = create("red_sandstone_stairs");
		public static final IOptionalNamedTag<Block> RED_SANDSTONE_WALLS = create("red_sandstone_walls");
		public static final IOptionalNamedTag<Block> CRACKED_BRICKS = create("cracked_bricks");
		public static final IOptionalNamedTag<Block> CRACKED_BRICK_SLABS = create("cracked_brick_slabs");
		public static final IOptionalNamedTag<Block> CRACKED_BRICK_STAIRS = create("cracked_brick_stairs");
		public static final IOptionalNamedTag<Block> CRACKED_BRICK_WALLS = create("cracked_brick_walls");
		public static final IOptionalNamedTag<Block> STONE_BRICKS = create("stone_bricks");
		public static final IOptionalNamedTag<Block> STONE_BRICK_SLABS = create("stone_brick_slabs");
		public static final IOptionalNamedTag<Block> STONE_BRICK_STAIRS = create("stone_brick_stairs");
		public static final IOptionalNamedTag<Block> STONE_BRICK_WALLS = create("stone_brick_walls");
		public static final IOptionalNamedTag<Block> SMOOTH_STONE = create("smooth_stone");
		public static final IOptionalNamedTag<Block> SMOOTH_STONE_SLABS = create("smooth_stone_slabs");
		public static final IOptionalNamedTag<Block> SMOOTH_STONE_STAIRS = create("smooth_stone_stairs");
		public static final IOptionalNamedTag<Block> SMOOTH_STONE_WALLS = create("smooth_stone_walls");
		public static final IOptionalNamedTag<Block> STONE = create("stone");
		public static final IOptionalNamedTag<Block> STONE_SLABS = create("stone_slabs");
		public static final IOptionalNamedTag<Block> STONE_STAIRS = create("stone_stairs");
		public static final IOptionalNamedTag<Block> STONE_WALLS = create("stone_walls");
		public static final IOptionalNamedTag<Block> OAK_SLABS = create("oak_slabs");
		public static final IOptionalNamedTag<Block> OAK_STAIRS = create("oak_stairs");
		public static final IOptionalNamedTag<Block> OAK_WALLS = create("oak_walls");	
		public static final IOptionalNamedTag<Block> SPRUCE_SLABS = create("spruce_slabs");
		public static final IOptionalNamedTag<Block> SPRUCE_STAIRS = create("spruce_stairs");
		public static final IOptionalNamedTag<Block> SPRUCE_WALLS = create("spruce_walls");	
		public static final IOptionalNamedTag<Block> BIRCH_SLABS = create("birch_slabs");
		public static final IOptionalNamedTag<Block> BIRCH_STAIRS = create("birch_stairs");
		public static final IOptionalNamedTag<Block> BIRCH_WALLS = create("birch_walls");	
		public static final IOptionalNamedTag<Block> JUNGLE_SLABS = create("jungle_slabs");
		public static final IOptionalNamedTag<Block> JUNGLE_STAIRS = create("jungle_stairs");
		public static final IOptionalNamedTag<Block> JUNGLE_WALLS = create("jungle_walls");	
		public static final IOptionalNamedTag<Block> ACACIA_SLABS = create("acacia_slabs");
		public static final IOptionalNamedTag<Block> ACACIA_STAIRS = create("acacia_stairs");
		public static final IOptionalNamedTag<Block> ACACIA_WALLS = create("acacia_walls");	
		public static final IOptionalNamedTag<Block> DARK_OAK_SLABS = create("dark_oak_slabs");
		public static final IOptionalNamedTag<Block> DARK_OAK_STAIRS = create("dark_oak_stairs");
		public static final IOptionalNamedTag<Block> DARK_OAK_WALLS = create("dark_oak_walls");	
		public static final IOptionalNamedTag<Block> CRIMSON_SLABS = create("crimson_slabs");
		public static final IOptionalNamedTag<Block> CRIMSON_STAIRS = create("crimson_stairs");
		public static final IOptionalNamedTag<Block> CRIMSON_WALLS = create("crimson_walls");	
		public static final IOptionalNamedTag<Block> WARPED_SLABS = create("crimson_slabs");
		public static final IOptionalNamedTag<Block> WARPED_STAIRS = create("crimson_stairs");
		public static final IOptionalNamedTag<Block> WARPED_WALLS = create("crimson_walls");
		public static final IOptionalNamedTag<Block> OBSIDIAN = create("obsidian");
		public static final IOptionalNamedTag<Block> OBSIDIAN_SLABS = create("obsidian_slabs");
		public static final IOptionalNamedTag<Block> OBSIDIAN_STAIRS = create("obsidian_stairs");
		public static final IOptionalNamedTag<Block> OBSIDIAN_WALLS = create("obsidian_walls");
		
		private static IOptionalNamedTag<Block> create(String name) {
			return BlockTags.createOptional(new ResourceLocation(SSWPlusMain.MODID, name));
		}
	}
	
	public static class ItemTagList {
		public static final IOptionalNamedTag<Item> WOODEN_WALLS = create("wooden_walls");
		public static final IOptionalNamedTag<Item> GLASS_SLABS = create("glass_slabs");
		public static final IOptionalNamedTag<Item> GLASS_STAIRS = create("glass_stairs");
		public static final IOptionalNamedTag<Item> GLASS_WALLS = create("glass_walls");
		public static final IOptionalNamedTag<Item> COLORED_GLASS_SLABS = create("colored_glass_slabs");
		public static final IOptionalNamedTag<Item> COLORED_GLASS_STAIRS = create("colored_glass_stairs");
		public static final IOptionalNamedTag<Item> COLORED_GLASS_WALLS = create("colored_glass_walls");
		public static final IOptionalNamedTag<Item> TERRACOTTA_SLABS = create("terracotta_slabs");
		public static final IOptionalNamedTag<Item> TERRACOTTA_STAIRS = create("terracotta_stairs");
		public static final IOptionalNamedTag<Item> TERRACOTTA_WALLS = create("terracotta_walls");
		public static final IOptionalNamedTag<Item> COLORED_TERRACOTTA_SLABS = create("colored_terracotta_slabs");
		public static final IOptionalNamedTag<Item> COLORED_TERRACOTTA_STAIRS = create("colored_terracotta_stairs");
		public static final IOptionalNamedTag<Item> COLORED_TERRACOTTA_WALLS = create("colored_terracotta_walls");
		public static final IOptionalNamedTag<Item> CONCRETE_SLABS = create("concrete_slabs");
		public static final IOptionalNamedTag<Item> CONCRETE_STAIRS = create("concrete_stairs");
		public static final IOptionalNamedTag<Item> CONCRETE_WALLS = create("concrete_walls");
		public static final IOptionalNamedTag<Item> ANDESITE = create("andesite");
		public static final IOptionalNamedTag<Item> ANDESITE_SLABS = create("andesite_slabs");
		public static final IOptionalNamedTag<Item> ANDESITE_STAIRS = create("andesite_stairs");
		public static final IOptionalNamedTag<Item> ANDESITE_WALLS = create("andesite_walls");
		public static final IOptionalNamedTag<Item> DIORITE = create("diorite");
		public static final IOptionalNamedTag<Item> DIORITE_SLABS = create("diorite_slabs");
		public static final IOptionalNamedTag<Item> DIORITE_STAIRS = create("diorite_stairs");
		public static final IOptionalNamedTag<Item> DIORITE_WALLS = create("diorite_walls");
		public static final IOptionalNamedTag<Item> GRANITE = create("granite");
		public static final IOptionalNamedTag<Item> GRANITE_SLABS = create("granite_slabs");
		public static final IOptionalNamedTag<Item> GRANITE_STAIRS = create("granite_stairs");
		public static final IOptionalNamedTag<Item> GRANITE_WALLS = create("granite_walls");
		public static final IOptionalNamedTag<Item> BASALT = create("basalt");
		public static final IOptionalNamedTag<Item> BASALT_SLABS = create("basalt_slabs");
		public static final IOptionalNamedTag<Item> BASALT_STAIRS = create("basalt_stairs");
		public static final IOptionalNamedTag<Item> BASALT_WALLS = create("basalt_walls");
		public static final IOptionalNamedTag<Item> BLACKSTONE = create("blackstone");
		public static final IOptionalNamedTag<Item> BLACKSTONE_SLABS = create("blackstone_slabs");
		public static final IOptionalNamedTag<Item> BLACKSTONE_STAIRS = create("blackstone_stairs");
		public static final IOptionalNamedTag<Item> BLACKSTONE_WALLS = create("blackstone_walls");
		public static final IOptionalNamedTag<Item> NETHER_BRICKS = create("nether_bricks");
		public static final IOptionalNamedTag<Item> NETHER_BRICK_SLABS = create("nether_brick_slabs");
		public static final IOptionalNamedTag<Item> NETHER_BRICK_STAIRS = create("nether_brick_stairs");
		public static final IOptionalNamedTag<Item> NETHER_BRICK_WALLS = create("nether_brick_walls");
		public static final IOptionalNamedTag<Item> PRISMARINE = create("prismarine");
		public static final IOptionalNamedTag<Item> PRISMARINE_SLABS = create("prismarine_slabs");
		public static final IOptionalNamedTag<Item> PRISMARINE_STAIRS = create("prismarine_stairs");
		public static final IOptionalNamedTag<Item> PRISMARINE_WALLS = create("prismarine_walls");
		public static final IOptionalNamedTag<Item> QUARTZ = create("quartz");
		public static final IOptionalNamedTag<Item> QUARTZ_SLABS = create("quartz_slabs");
		public static final IOptionalNamedTag<Item> QUARTZ_STAIRS = create("quartz_stairs");
		public static final IOptionalNamedTag<Item> QUARTZ_WALLS = create("quartz_walls");
		public static final IOptionalNamedTag<Item> SANDSTONE = create("sandstone");
		public static final IOptionalNamedTag<Item> SANDSTONE_SLABS = create("sandstone_slabs");
		public static final IOptionalNamedTag<Item> SANDSTONE_STAIRS = create("sandstone_stairs");
		public static final IOptionalNamedTag<Item> SANDSTONE_WALLS = create("sandstone_walls");
		public static final IOptionalNamedTag<Item> RED_SANDSTONE = create("red_sandstone");
		public static final IOptionalNamedTag<Item> RED_SANDSTONE_SLABS = create("red_sandstone_slabs");
		public static final IOptionalNamedTag<Item> RED_SANDSTONE_STAIRS = create("red_sandstone_stairs");
		public static final IOptionalNamedTag<Item> RED_SANDSTONE_WALLS = create("red_sandstone_walls");
		public static final IOptionalNamedTag<Item> CRACKED_BRICKS = create("cracked_bricks");
		public static final IOptionalNamedTag<Item> CRACKED_BRICK_SLABS = create("cracked_brick_slabs");
		public static final IOptionalNamedTag<Item> CRACKED_BRICK_STAIRS = create("cracked_brick_stairs");
		public static final IOptionalNamedTag<Item> CRACKED_BRICK_WALLS = create("cracked_brick_walls");
		public static final IOptionalNamedTag<Item> STONE_BRICKS = create("stone_bricks");
		public static final IOptionalNamedTag<Item> STONE_BRICK_SLABS = create("stone_brick_slabs");
		public static final IOptionalNamedTag<Item> STONE_BRICK_STAIRS = create("stone_brick_stairs");
		public static final IOptionalNamedTag<Item> STONE_BRICK_WALLS = create("stone_brick_walls");
		public static final IOptionalNamedTag<Item> SMOOTH_STONE = create("smooth_stone");
		public static final IOptionalNamedTag<Item> SMOOTH_STONE_SLABS = create("smooth_stone_slabs");
		public static final IOptionalNamedTag<Item> SMOOTH_STONE_STAIRS = create("smooth_stone_stairs");
		public static final IOptionalNamedTag<Item> SMOOTH_STONE_WALLS = create("smooth_stone_walls");
		public static final IOptionalNamedTag<Item> STONE = create("stone");
		public static final IOptionalNamedTag<Item> STONE_SLABS = create("stone_slabs");
		public static final IOptionalNamedTag<Item> STONE_STAIRS = create("stone_stairs");
		public static final IOptionalNamedTag<Item> STONE_WALLS = create("stone_walls");
		public static final IOptionalNamedTag<Item> OAK_SLABS = create("oak_slabs");
		public static final IOptionalNamedTag<Item> OAK_STAIRS = create("oak_stairs");
		public static final IOptionalNamedTag<Item> OAK_WALLS = create("oak_walls");	
		public static final IOptionalNamedTag<Item> SPRUCE_SLABS = create("spruce_slabs");
		public static final IOptionalNamedTag<Item> SPRUCE_STAIRS = create("spruce_stairs");
		public static final IOptionalNamedTag<Item> SPRUCE_WALLS = create("spruce_walls");	
		public static final IOptionalNamedTag<Item> BIRCH_SLABS = create("birch_slabs");
		public static final IOptionalNamedTag<Item> BIRCH_STAIRS = create("birch_stairs");
		public static final IOptionalNamedTag<Item> BIRCH_WALLS = create("birch_walls");	
		public static final IOptionalNamedTag<Item> JUNGLE_SLABS = create("jungle_slabs");
		public static final IOptionalNamedTag<Item> JUNGLE_STAIRS = create("jungle_stairs");
		public static final IOptionalNamedTag<Item> JUNGLE_WALLS = create("jungle_walls");	
		public static final IOptionalNamedTag<Item> ACACIA_SLABS = create("acacia_slabs");
		public static final IOptionalNamedTag<Item> ACACIA_STAIRS = create("acacia_stairs");
		public static final IOptionalNamedTag<Item> ACACIA_WALLS = create("acacia_walls");	
		public static final IOptionalNamedTag<Item> DARK_OAK_SLABS = create("dark_oak_slabs");
		public static final IOptionalNamedTag<Item> DARK_OAK_STAIRS = create("dark_oak_stairs");
		public static final IOptionalNamedTag<Item> DARK_OAK_WALLS = create("dark_oak_walls");	
		public static final IOptionalNamedTag<Item> CRIMSON_SLABS = create("crimson_slabs");
		public static final IOptionalNamedTag<Item> CRIMSON_STAIRS = create("crimson_stairs");
		public static final IOptionalNamedTag<Item> CRIMSON_WALLS = create("crimson_walls");	
		public static final IOptionalNamedTag<Item> WARPED_SLABS = create("crimson_slabs");
		public static final IOptionalNamedTag<Item> WARPED_STAIRS = create("crimson_stairs");
		public static final IOptionalNamedTag<Item> WARPED_WALLS = create("crimson_walls");
		public static final IOptionalNamedTag<Item> OBSIDIAN = create("obsidian");
		public static final IOptionalNamedTag<Item> OBSIDIAN_SLABS = create("obsidian_slabs");
		public static final IOptionalNamedTag<Item> OBSIDIAN_STAIRS = create("obsidian_stairs");
		public static final IOptionalNamedTag<Item> OBSIDIAN_WALLS = create("obsidian_walls");
		
		
		private static IOptionalNamedTag<Item> create(String name) {
			return ItemTags.createOptional(new ResourceLocation(SSWPlusMain.MODID, name));
		}
	}
}